// Generated by `npm run gen` (scripts/generate-cli-data.mjs) — do not edit by hand.
export default {
  "backgroundEffects": [
    "static",
    "slow-zoom-in",
    "slow-zoom-out",
    "ken-burns",
    "drift",
    "pulse",
    "breathe",
    "slow-tilt",
    "camera-shake"
  ],
  "stylePresets": {
    "default": "bold",
    "ids": [
      "bold",
      "editorial",
      "stark"
    ]
  },
  "aliases": {
    "chatConversation": "chatMessenger",
    "chatBubbles": "chatMessenger",
    "whatsappChat": "chatWhatsapp",
    "browserMockup": "webMockup",
    "browserSlides": "webMockup",
    "tabletMockup": "webMockup",
    "tabletSlides": "webMockup",
    "triplePhone": "phoneMockup",
    "emojiRain": "beforeAfter",
    "comparison": "problemSolution",
    "pieChart": "barChart",
    "ctaProof": "ctaMedia",
    "googleSearch": "tweet",
    "appFeed": "notification"
  },
  "formats": {
    "launch": {
      "id": "launch",
      "description": "Tech/SaaS launch moment: hook → 3 bodies (framing, comprehension, proof) → closer. Default 5 scenes at each template's preferredDuration, typically 15-20s total. 4 scenes only for explicitly simple/short input; bodies grow beyond 3 only when the user provides 4+ specific assets that each deserve their own scene (cap 6 bodies).",
      "slots": {
        "hook": {
          "bannedTemplateIds": [
            "chatWhatsapp",
            "chatMessenger",
            "appFeed",
            "problemSolution",
            "beforeAfter"
          ],
          "defaultTemplateId": "media"
        },
        "body": {
          "roleBudget": [
            "framing",
            "comprehension",
            "proof"
          ],
          "min": 1,
          "max": 6,
          "default": 3
        },
        "closer": {
          "requiredCategory": "closer",
          "onlyInFinalSlot": true
        }
      },
      "sceneCount": {
        "min": 3,
        "max": 8,
        "default": 5
      },
      "diversity": {
        "noSameCategoryAdjacent": true,
        "noSameTemplateAdjacent": true,
        "adjacencyExemptCategories": [
          "media"
        ]
      }
    },
    "review": {
      "id": "review",
      "description": "Customer review moment: hook → 2-3 bodies (the quote, who they are, what changed) → closer. The quote must be real and attributed — never invent a reviewer, a company or a number. Default 5 scenes, typically 15-20s.",
      "slots": {
        "hook": {
          "bannedTemplateIds": [
            "chatWhatsapp",
            "chatMessenger",
            "appFeed",
            "problemSolution",
            "beforeAfter",
            "testimonial",
            "reviewStack"
          ],
          "defaultTemplateId": "media"
        },
        "body": {
          "roleBudget": [
            "quote",
            "attribution",
            "outcome"
          ],
          "min": 2,
          "max": 5,
          "default": 3
        },
        "closer": {
          "requiredCategory": "closer",
          "onlyInFinalSlot": true
        }
      },
      "sceneCount": {
        "min": 4,
        "max": 7,
        "default": 5
      },
      "diversity": {
        "noSameCategoryAdjacent": true,
        "noSameTemplateAdjacent": true,
        "adjacencyExemptCategories": [
          "media"
        ]
      }
    },
    "milestone": {
      "id": "milestone",
      "description": "Numeric achievement: hook → 2-3 bodies (the number, the context, the thanks) → closer. Use the exact figure from the input; never round up an invented one. Default 4 scenes, typically 12-16s — a milestone outstays its welcome faster than a launch.",
      "slots": {
        "hook": {
          "bannedTemplateIds": [
            "chatWhatsapp",
            "chatMessenger",
            "appFeed",
            "problemSolution",
            "beforeAfter",
            "milestone",
            "bigNumber"
          ],
          "defaultTemplateId": "media"
        },
        "body": {
          "roleBudget": [
            "number",
            "context",
            "gratitude"
          ],
          "min": 2,
          "max": 4,
          "default": 2
        },
        "closer": {
          "requiredCategory": "closer",
          "onlyInFinalSlot": true
        }
      },
      "sceneCount": {
        "min": 3,
        "max": 6,
        "default": 4
      },
      "diversity": {
        "noSameCategoryAdjacent": true,
        "noSameTemplateAdjacent": true,
        "adjacencyExemptCategories": [
          "media"
        ]
      }
    },
    "update": {
      "id": "update",
      "description": "Product update / changelog: hook → 2-4 bodies (what changed, what it looks like, why it matters) → closer. Show the actual surface that changed — a real screenshot beats a synthesized one. Default 5 scenes, typically 14-18s.",
      "slots": {
        "hook": {
          "bannedTemplateIds": [
            "chatWhatsapp",
            "chatMessenger",
            "appFeed",
            "problemSolution",
            "beforeAfter"
          ],
          "defaultTemplateId": "media"
        },
        "body": {
          "roleBudget": [
            "change",
            "demonstration",
            "benefit"
          ],
          "min": 2,
          "max": 5,
          "default": 3
        },
        "closer": {
          "requiredCategory": "closer",
          "onlyInFinalSlot": true
        }
      },
      "sceneCount": {
        "min": 4,
        "max": 7,
        "default": 5
      },
      "diversity": {
        "noSameCategoryAdjacent": true,
        "noSameTemplateAdjacent": true,
        "adjacencyExemptCategories": [
          "media"
        ]
      }
    }
  },
  "customScene": {
    "idPrefix": "custom_",
    "maxSourceChars": 16000,
    "bannedTokens": [
      {
        "source": "\\bMath\\.random\\b",
        "flags": "",
        "reason": "Math.random breaks export determinism — seed with a hash of variables instead"
      },
      {
        "source": "\\bDate\\.now\\b",
        "flags": "",
        "reason": "Date.now breaks determinism"
      },
      {
        "source": "\\bnew\\s+Date\\b",
        "flags": "",
        "reason": "new Date() breaks determinism"
      },
      {
        "source": "\\bperformance\\.now\\b",
        "flags": "",
        "reason": "performance.now breaks determinism"
      },
      {
        "source": "\\bsetTimeout\\b",
        "flags": "",
        "reason": "setTimeout breaks deterministic rendering"
      },
      {
        "source": "\\bsetInterval\\b",
        "flags": "",
        "reason": "setInterval breaks deterministic rendering"
      },
      {
        "source": "\\brequestAnimationFrame\\b",
        "flags": "",
        "reason": "requestAnimationFrame breaks deterministic rendering — use the progress prop"
      },
      {
        "source": "\\bimport\\s*[({]",
        "flags": "",
        "reason": "dynamic import is not allowed"
      },
      {
        "source": "\\bimport\\s+[{\\w*\"']",
        "flags": "",
        "reason": "static imports are not allowed — helpers are in scope"
      },
      {
        "source": "^\\s*export\\s+",
        "flags": "m",
        "reason": "exports are not allowed — define a single `Component` function"
      },
      {
        "source": "\\bclassName\\s*[:=]",
        "flags": "",
        "reason": "className not allowed — use inline style={{ ... }}"
      },
      {
        "source": "\\bdangerouslySetInnerHTML\\b",
        "flags": "",
        "reason": "dangerouslySetInnerHTML not allowed — write the JSX directly"
      },
      {
        "source": "\\son(?:error|click|load|focus|focusin|focusout|mouseenter|mouseover|mouseout|mousemove|input|change|submit|toggle|abort|animationend|transitionend|drag|drop|paste|copy|cut|keydown|keyup|keypress|select|wheel|scroll|contextmenu|reset|invalid|beforeunload|unload)\\s*=",
        "flags": "i",
        "reason": "HTML event handler attributes not allowed — templates are pure animation"
      },
      {
        "source": "javascript\\s*:",
        "flags": "i",
        "reason": "javascript: URIs not allowed"
      },
      {
        "source": "<\\s*script\\b",
        "flags": "i",
        "reason": "<script> tags not allowed"
      },
      {
        "source": "\\bgradientBackground\\s*\\(",
        "flags": "",
        "reason": "do not call gradientBackground — the brand gradient is rendered by <SceneFrame> around your body"
      },
      {
        "source": "\\b(?:TitleTop|TitleCenter)\\b",
        "flags": "",
        "reason": "do not render TitleTop/TitleCenter — the main title is rendered by <SceneFrame> around your body"
      }
    ],
    "scopeNames": [
      "BarChart",
      "BeforeAfterSplit",
      "BrandMessageBubble",
      "CodeEditor",
      "ConversationThread",
      "CountUpNumber",
      "CtaMediaClose",
      "EASE",
      "Easing",
      "FeatureGrid",
      "FeatureList",
      "Fragment",
      "IncomingCallCard",
      "Math",
      "MilestoneBadge",
      "NotificationCard",
      "PhoneFrame",
      "ProblemSolution",
      "ProgressRing",
      "PromptInputPill",
      "React",
      "ReactionClip",
      "ReviewStack",
      "SPRING_BOUNCY",
      "SPRING_SMOOTH",
      "SPRING_SNAPPY",
      "StatBadgeRow",
      "StepsList",
      "TEXT_ARCHETYPES",
      "TemplateText",
      "TerminalOutput",
      "TestimonialCard",
      "TweetCard",
      "WebMockup",
      "WordmarkReveal",
      "autoTextColor",
      "burst",
      "cascade",
      "center",
      "countUp",
      "createElement",
      "cubicBezier",
      "drift",
      "fitTextSize",
      "getResponsiveFontSize",
      "glow",
      "grain",
      "interpolate",
      "isColorDark",
      "meshGradient",
      "morph",
      "orbit",
      "orderDarkToLight",
      "particles",
      "pathDraw",
      "phase",
      "punch",
      "rand01",
      "shiftHue",
      "softShadow",
      "spring",
      "stagger",
      "staggerWindow",
      "stripPipe",
      "sweep",
      "typewriter",
      "useCallback",
      "useEffect",
      "useMemo",
      "useRef",
      "useState",
      "vignette",
      "withOpacity"
    ],
    "scopeDocs": {
      "autoTextColor": {
        "sig": "autoTextColor(background) → \"#fff\" | \"#000\"",
        "use": "Pick legible text for an arbitrary background. Use whenever the backdrop colour is data-driven."
      },
      "burst": {
        "sig": "burst(count, progress, { radius?, spread?, seed? }) → Particle[]",
        "use": "Radial one-shot emission from a point. For impacts and celebrations."
      },
      "cascade": {
        "sig": "cascade(text, progress, { overlap?, easing? }) → CascadeItem[]",
        "use": "Per-word or per-character reveal data for a line of copy. Prefer this to hand-slicing strings."
      },
      "center": {
        "sig": "center(xPct?, yPct?, extraTransform?) → CSSProperties",
        "use": "Absolute-centre an element without hand-writing the translate. Append your own transform via the third argument so you don't clobber the centring."
      },
      "countUp": {
        "sig": "countUp(progress, target, { from?, easing?, format? }) → { value, display }",
        "use": "Roll a number up to a target. Only use with a real figure from the brief — never a placeholder."
      },
      "cubicBezier": {
        "sig": "cubicBezier(x1, y1, x2, y2) → (t) => number",
        "use": "Build a custom curve when the named EASE set genuinely has no fit. Prefer EASE first."
      },
      "drift": {
        "sig": "drift(progress, { amount?, speed?, axis? }) → transform string",
        "use": "Slow ambient float. Keeps a static composition alive without pulling focus — good on backgrounds and idle objects."
      },
      "EASE": {
        "sig": "EASE.<name>",
        "use": "Named curves already tuned for scene work — reach here before composing your own bezier, so motion reads consistently across scenes."
      },
      "Easing": {
        "sig": "Easing.bezier(a,b,c,d) · Easing.out(Easing.cubic) · linear|quad|cubic|sin|exp|circle · in|out|inOut",
        "use": "Curve constructors. `Easing.out(Easing.cubic)` is the default for anything entering; `inOut` for anything that travels across the frame and settles."
      },
      "fitTextSize": {
        "sig": "fitTextSize(text, baseSize, maxWidth, opts?) → number",
        "use": "Shrink-to-fit for fixed-width containers. Use it rather than guessing a size — the export rasteriser renders text a few percent wider than the preview, so anything tuned by eye can overflow."
      },
      "getResponsiveFontSize": {
        "sig": "getResponsiveFontSize(length, base, min, max) → number",
        "use": "Scale type down as copy gets longer. For slots whose text length varies."
      },
      "glow": {
        "sig": "glow(color, { size?, x?, y?, intensity? }) → CSSProperties",
        "use": "A soft radial bloom. Layer two or three at different sizes for depth. Build glows from this rather than a large blurred box-shadow, which bands into a visible rectangle at scale."
      },
      "grain": {
        "sig": "grain(opacity?, seed?) → CSSProperties",
        "use": "Film grain overlay. Takes the plastic sheen off large flat gradients."
      },
      "interpolate": {
        "sig": "interpolate(value, inputRange, outputRange, { easing?, extrapolateLeft?, extrapolateRight? })",
        "use": "Map progress onto any numeric range. Pass `extrapolate*: \"clamp\"` unless you want the value to keep running past the window — unclamped values sliding out of range is the most common cause of an element that drifts off-frame."
      },
      "isColorDark": {
        "sig": "isColorDark(color) → boolean",
        "use": "Branch on background luminance."
      },
      "meshGradient": {
        "sig": "meshGradient(colors, seed?) → background string",
        "use": "Multi-stop colour field. Note the frame already paints the brand background — use this inside an element, not as a full-bleed backdrop."
      },
      "morph": {
        "sig": "morph(progress, fromValue, toValue, easing?)",
        "use": "Interpolate between two shapes/values as one unit."
      },
      "orbit": {
        "sig": "orbit(progress, { radius, speed?, phase? }) → { x, y, deg }",
        "use": "Circular travel. Also the cheapest way to make several elements move as a related system rather than independently."
      },
      "orderDarkToLight": {
        "sig": "orderDarkToLight(colors) → colors",
        "use": "Sort a palette so gradients and stacks read consistently."
      },
      "particles": {
        "sig": "particles(count, progress, { spread?, gravity?, seed?, easing? }) → Particle[]",
        "use": "Deterministic particle field. Seeded, so it renders identically every time — never reach for Math.random, which the sandbox rejects."
      },
      "pathDraw": {
        "sig": "pathDraw(progress, pathLength, { easing? }) → { strokeDasharray, strokeDashoffset }",
        "use": "Stroke an SVG path on as progress advances. Use for diagrams, routes, filaments — anything whose construction is the story. Normalise your per-item stagger with staggerWindow so every path finishes inside the scene."
      },
      "phase": {
        "sig": "phase(progress, [start, end], easing?) → 0..1",
        "use": "Remap scene progress to a local 0..1 inside one beat, clamped. The backbone of multi-beat scenes — reach for this before writing a bare interpolate for enter/hold/exit."
      },
      "punch": {
        "sig": "punch(progress, { at?, width?, amount? }) → scale multiplier",
        "use": "A 1 → 1+amount → 1 bump around a moment. Multiply into a transform for beat hits and emphasis."
      },
      "rand01": {
        "sig": "rand01(seed, index?) → 0..1",
        "use": "Deterministic pseudo-random. The ONLY sanctioned source of randomness in a custom scene. For an even spread over a disc, prefer a golden-angle spiral over repeated rand01 draws — random angles clump into visible arcs."
      },
      "shiftHue": {
        "sig": "shiftHue(color, degrees) → color",
        "use": "Derive a related hue from the accent — the sanctioned way to get a second brand colour instead of inventing one."
      },
      "softShadow": {
        "sig": "softShadow(elevation?, color?) → boxShadow string",
        "use": "Consistent elevation for cards and floating chrome."
      },
      "spring": {
        "sig": "spring(progress, { damping, stiffness }) → number",
        "use": "Spring-shaped easing over a 0..1 input. Feed it a phase()/interpolate() result, not raw time. Pair with the SPRING_* presets rather than inventing constants."
      },
      "SPRING_BOUNCY": {
        "sig": "SPRING_BOUNCY",
        "use": "Overshoots visibly. For celebratory pops and stamps — one per scene at most, or it reads cartoonish."
      },
      "SPRING_SMOOTH": {
        "sig": "SPRING_SMOOTH",
        "use": "Settled, no visible bounce. The default for entrances that shouldn't draw attention to themselves."
      },
      "SPRING_SNAPPY": {
        "sig": "SPRING_SNAPPY",
        "use": "Fast and tight. For elements that should feel mechanical or instant."
      },
      "stagger": {
        "sig": "stagger(progress, index, total, staggerDelay?, startAt?) → 0..1",
        "use": "Delay-based sibling of staggerWindow: each item waits its turn by a fixed delay. Use when the gap between items matters more than filling the scene; use staggerWindow when every item must finish inside the beat."
      },
      "staggerWindow": {
        "sig": "staggerWindow(progress, index, count, { overlap?, from?, seed?, easing? }) → 0..1",
        "use": "Per-item progress for a group, with overlapping windows normalised so item 0 starts at 0 and the LAST item ends exactly at 1. Always prefer this to a hand-rolled `start + i * step`, which silently pushes late items past 1.0 so they never animate. `from: \"center\"` radiates outward; `\"random\"` is seeded and therefore deterministic."
      },
      "stripPipe": {
        "sig": "stripPipe(text) → string",
        "use": "Strip the `|` line-break marker from authored copy before measuring or rendering it raw."
      },
      "sweep": {
        "sig": "sweep(progress, { from?, to?, softness? })",
        "use": "A band of light or attention travelling across the frame. Use when the subject is 'something is being scanned or read'."
      },
      "TemplateText": {
        "sig": "<TemplateText text archetype progress … />",
        "use": "Render copy with a text archetype's full entrance/hold/exit lifecycle instead of hand-animating opacity."
      },
      "TEXT_ARCHETYPES": {
        "sig": "TEXT_ARCHETYPES",
        "use": "The archetype table (subtle, typewriter, wordStagger, slam, cinematic, heroWord) — read it to pick a lifecycle rather than inventing one."
      },
      "typewriter": {
        "sig": "typewriter(text, progress, { cursor? }) → { shown, caretVisible }",
        "use": "Character-by-character typing with a caret. For terminal/prompt moments — deterministic, unlike a timer-driven cursor."
      },
      "vignette": {
        "sig": "vignette(strength?) → CSSProperties",
        "use": "Darken the frame edges to hold the eye centre-frame. Cheap depth on an otherwise flat composition."
      },
      "withOpacity": {
        "sig": "withOpacity(color, alpha) → rgba string",
        "use": "Fade a token colour without hardcoding an rgba literal."
      }
    }
  },
  "templates": {
    "media": {
      "category": "media",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 1,
      "preferredDuration": 2,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "textColor": {
          "type": "color"
        },
        "confetti": {
          "type": "boolean"
        }
      },
      "defaultVariables": {
        "texts": "Make an impact.",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "textColor": "",
        "confetti": false
      }
    },
    "reaction": {
      "category": "media",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "reactionTag": {
          "type": "enum",
          "required": true,
          "options": [
            "launch",
            "productLaunch",
            "goLive",
            "shipIt",
            "wow",
            "excited",
            "happy",
            "success",
            "done",
            "panic",
            "waiting",
            "celebration",
            "cheers",
            "applause",
            "highFive",
            "teamwork",
            "fail",
            "confused",
            "thinking",
            "thanks",
            "letsGo",
            "manual",
            "office",
            "meeting",
            "deadline",
            "coding",
            "debugging",
            "computer",
            "startup",
            "presentation",
            "sales",
            "growth",
            "money"
          ]
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaType": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "texts": "Still editing manually?",
        "reactionTag": "manual",
        "mediaUrl": "",
        "mediaType": "video"
      }
    },
    "confetti": {
      "category": "celebration",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 1,
      "preferredDuration": 2,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Celebrate.",
        "textColor": ""
      }
    },
    "emojiBurst": {
      "category": "celebration",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 1,
      "preferredDuration": 2,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Let's go!",
        "textColor": ""
      }
    },
    "bigNumber": {
      "category": "data",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 1.5,
      "preferredDuration": 4,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "value": {
          "type": "number",
          "required": true
        },
        "label": {
          "type": "string",
          "required": true
        },
        "prefix": {
          "type": "string"
        },
        "unit": {
          "type": "string"
        },
        "chartColor": {
          "type": "color"
        },
        "textColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "texts": "Our biggest milestone yet.",
        "value": 1000,
        "label": "Total users",
        "prefix": "",
        "unit": "",
        "chartColor": "#00e5a0",
        "textColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "barChart": {
      "category": "data",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "bars": {
          "type": "string"
        },
        "chartColor": {
          "type": "color"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Revenue up 300%.",
        "bars": "30,55,45,80,65,95",
        "chartColor": "#00e5a0",
        "textColor": ""
      }
    },
    "progressRing": {
      "category": "data",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "value": {
          "type": "number",
          "required": true
        },
        "label": {
          "type": "string",
          "required": true
        },
        "unit": {
          "type": "string"
        },
        "chartColor": {
          "type": "color"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Almost there.",
        "value": 75,
        "label": "Complete",
        "unit": "%",
        "chartColor": "#00e5a0",
        "textColor": ""
      }
    },
    "phoneMockup": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "screenMediaUrl": {
          "type": "media"
        },
        "screen1Url": {
          "type": "media"
        },
        "screen2Url": {
          "type": "media"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "See it in action.",
        "screenMediaUrl": "",
        "screen1Url": "",
        "screen2Url": "",
        "textColor": ""
      }
    },
    "webMockup": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "frame": {
          "type": "enum",
          "options": [
            "browser",
            "tablet"
          ]
        },
        "texts": {
          "type": "string",
          "required": true
        },
        "screenMediaUrl": {
          "type": "media"
        },
        "screen1Url": {
          "type": "media"
        },
        "screen2Url": {
          "type": "media"
        },
        "addressBarUrl": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "frame": "browser",
        "texts": "See it in action.",
        "screenMediaUrl": "",
        "screen1Url": "",
        "screen2Url": "",
        "addressBarUrl": "yourapp.com",
        "textColor": ""
      }
    },
    "codeEditor": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "code": {
          "type": "string",
          "required": true
        },
        "filename": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Simple as this.",
        "code": "import { create } from \"vanillasky\";\n\nconst video = await create({\n  prompt: \"Launch trailer\",\n  style: \"cinematic\",\n});\n\nconsole.log(video.url);",
        "filename": "app.ts",
        "textColor": ""
      }
    },
    "terminal": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "command": {
          "type": "string",
          "required": true
        },
        "output": {
          "type": "string"
        },
        "promptPrefix": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Ship it.",
        "command": "npx vanillasky create --trailer",
        "output": "✓ Scenes composed,✓ Beat-synced to music,✓ Ready to export",
        "promptPrefix": "$",
        "textColor": ""
      }
    },
    "tweet": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 3.5,
      "variableSchema": {
        "authorName": {
          "type": "string",
          "required": true
        },
        "authorHandle": {
          "type": "string"
        },
        "authorVerified": {
          "type": "boolean"
        },
        "message": {
          "type": "string",
          "required": true
        },
        "likes": {
          "type": "number"
        },
        "replies": {
          "type": "number"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "authorName": "Your brand",
        "authorHandle": "",
        "authorVerified": true,
        "message": "Just shipped the new feature 🚀",
        "likes": 602,
        "replies": 19,
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "notification": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "appName": {
          "type": "string",
          "required": true
        },
        "appIcon": {
          "type": "string"
        },
        "message": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "appName": "Reminder",
        "appIcon": "🔔",
        "message": "Believe in your dreams, they will lead you.",
        "textColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "chatMessenger": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 5,
      "preferredDuration": 8,
      "variableSchema": {
        "msg1": {
          "type": "string",
          "required": true
        },
        "msg2": {
          "type": "string",
          "required": true
        },
        "msg3": {
          "type": "string",
          "required": true
        },
        "msg4": {
          "type": "string"
        },
        "dateChip1": {
          "type": "string"
        },
        "dateChip2": {
          "type": "string"
        },
        "msg5": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "theme": "messenger",
        "msg1": "Have you tried it yet?",
        "msg2": "It saves me hours every week",
        "msg3": "And the team loves it",
        "msg4": "Sounds great — sharing access now",
        "msg5": "",
        "dateChip1": "",
        "dateChip2": ""
      }
    },
    "chatWhatsapp": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 5,
      "preferredDuration": 8,
      "variableSchema": {
        "msg1": {
          "type": "string",
          "required": true
        },
        "msg2": {
          "type": "string",
          "required": true
        },
        "msg3": {
          "type": "string",
          "required": true
        },
        "msg4": {
          "type": "string"
        },
        "dateChip1": {
          "type": "string"
        },
        "dateChip2": {
          "type": "string"
        },
        "msg5": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "theme": "whatsapp",
        "msg1": "Have you tried it yet?",
        "msg2": "It saves me hours every week",
        "msg3": "And the team loves it",
        "msg4": "Sounds great — sharing access now",
        "msg5": "",
        "dateChip1": "",
        "dateChip2": ""
      }
    },
    "milestone": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "label": {
          "type": "string",
          "required": true
        },
        "targetNumber": {
          "type": "number",
          "required": true
        },
        "startNumber": {
          "type": "number"
        },
        "badgeText": {
          "type": "string"
        },
        "badgeEmoji": {
          "type": "string"
        },
        "badgeColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "label": "Followers",
        "targetNumber": 10000,
        "startNumber": "",
        "badgeText": "10K Followers!",
        "badgeEmoji": "🎉",
        "badgeColor": "#facc15",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "reviewStack": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "review1Title": {
          "type": "string",
          "required": true
        },
        "review1Body": {
          "type": "string"
        },
        "review1Author": {
          "type": "string"
        },
        "review2Title": {
          "type": "string",
          "required": true
        },
        "review2Body": {
          "type": "string"
        },
        "review2Author": {
          "type": "string"
        },
        "review3Title": {
          "type": "string",
          "required": true
        },
        "review3Body": {
          "type": "string"
        },
        "review3Author": {
          "type": "string"
        },
        "starColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "review1Title": "Life changing app",
        "review1Body": "Been using this for a month and can't imagine going back",
        "review1Author": "Sarah M.",
        "review2Title": "Best in class",
        "review2Body": "Finally an app that just works. No bloat, no nonsense.",
        "review2Author": "Mike R.",
        "review3Title": "Exceeded expectations",
        "review3Body": "Worth every penny. The team clearly cares about quality.",
        "review3Author": "Alex K.",
        "starColor": "#facc15",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "testimonial": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "quote": {
          "type": "string",
          "required": true
        },
        "authorName": {
          "type": "string",
          "required": true
        },
        "authorRole": {
          "type": "string"
        },
        "avatarColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "quote": "Best decision I made this year. Our conversion rate doubled in the first week.",
        "authorName": "Jessica Torres",
        "authorRole": "VP of Marketing, Acme Inc",
        "avatarColor": "#ec4899",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "incomingCall": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "callerName": {
          "type": "string",
          "required": true
        },
        "subtitle": {
          "type": "string"
        },
        "declineLabel": {
          "type": "string"
        },
        "acceptLabel": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "callerName": "Your brand",
        "subtitle": "is calling....",
        "declineLabel": "Decline",
        "acceptLabel": "Accept",
        "textColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "brandMessage": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "brandName": {
          "type": "string",
          "required": true
        },
        "message": {
          "type": "string",
          "required": true
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "brandName": "Your brand",
        "message": "We built this for you.",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "promptInput": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "promptText": {
          "type": "string",
          "required": true
        },
        "pillBg": {
          "type": "color"
        },
        "pillTextColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "promptText": "Make a launch video for our app",
        "pillBg": "",
        "pillTextColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "beforeAfter": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 3,
      "preferredDuration": 4.5,
      "variableSchema": {
        "problemLabel": {
          "type": "string"
        },
        "problemHeadline": {
          "type": "string",
          "required": true
        },
        "solutionLabel": {
          "type": "string"
        },
        "solutionHeadline": {
          "type": "string",
          "required": true
        },
        "problemEmojis": {
          "type": "string",
          "required": true
        },
        "solutionEmojis": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "problemLabel": "BEFORE",
        "problemHeadline": "Your calendar today.",
        "solutionLabel": "AFTER",
        "solutionHeadline": "Calmly organized.",
        "problemEmojis": "📅,😰,💼,📊,⏰,💬,📞,🔔",
        "solutionEmojis": "✨,📋,✅,🎯",
        "textColor": ""
      }
    },
    "tripleStats": {
      "category": "data",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "stat1Value": {
          "type": "string",
          "required": true
        },
        "stat1Label": {
          "type": "string",
          "required": true
        },
        "stat2Value": {
          "type": "string",
          "required": true
        },
        "stat2Label": {
          "type": "string",
          "required": true
        },
        "stat3Value": {
          "type": "string",
          "required": true
        },
        "stat3Label": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "By the numbers.",
        "stat1Value": "10K",
        "stat1Label": "Users",
        "stat2Value": "99.9%",
        "stat2Label": "Uptime",
        "stat3Value": "<50ms",
        "stat3Label": "Latency",
        "textColor": ""
      }
    },
    "problemSolution": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 3,
      "preferredDuration": 5.5,
      "variableSchema": {
        "problemLabel": {
          "type": "string"
        },
        "problemText": {
          "type": "string",
          "required": true
        },
        "solutionLabel": {
          "type": "string"
        },
        "solutionText": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "problemLabel": "THE PROBLEM",
        "problemText": "Teams waste 40% of time in meetings",
        "solutionLabel": "THE SOLUTION",
        "solutionText": "AI that summarizes in seconds",
        "textColor": ""
      }
    },
    "cardList": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "items": {
          "type": "string",
          "required": true
        },
        "itemEmojis": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "What you get.",
        "items": "Automate your savings on energy bills,Cleaner energy without raising your bill,Same account and service guaranteed",
        "itemEmojis": "💰,⚡,🔒",
        "textColor": ""
      }
    },
    "steps": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "steps": {
          "type": "string",
          "required": true
        },
        "stepEmojis": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "How it works.",
        "steps": "Describe,Preview,Export",
        "stepEmojis": "✍️,👀,🚀",
        "textColor": ""
      }
    },
    "ctaLogo": {
      "category": "closer",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "brandName": {
          "type": "string",
          "required": true
        },
        "url": {
          "type": "string"
        },
        "cta": {
          "type": "string"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "brandName": "VanillaSky",
        "url": "yoursite.com",
        "cta": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": "",
        "textColor": ""
      }
    },
    "ctaMedia": {
      "category": "closer",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 4,
      "variableSchema": {
        "headline": {
          "type": "string",
          "required": true
        },
        "url": {
          "type": "string"
        },
        "cta": {
          "type": "string"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "headline": "Make every moment count",
        "url": "www.yoursite.com",
        "cta": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": "",
        "textColor": ""
      }
    }
  }
};
