// Generated by `npm run gen` (scripts/generate-cli-data.mjs) — do not edit by hand.
export default {
  "backgroundEffects": [
    "static",
    "slow-zoom-in",
    "slow-zoom-out",
    "ken-burns",
    "drift",
    "pulse",
    "breathe",
    "slow-tilt",
    "camera-shake"
  ],
  "aliases": {
    "chatConversation": "chatMessenger",
    "chatBubbles": "chatMessenger",
    "whatsappChat": "chatWhatsapp",
    "browserMockup": "webMockup",
    "browserSlides": "webMockup",
    "tabletMockup": "webMockup",
    "tabletSlides": "webMockup",
    "triplePhone": "phoneMockup",
    "emojiRain": "beforeAfter",
    "comparison": "problemSolution",
    "pieChart": "barChart",
    "ctaProof": "ctaMedia",
    "googleSearch": "tweet",
    "appFeed": "notification"
  },
  "formats": {
    "launch": {
      "id": "launch",
      "description": "Tech/SaaS launch moment: hook → 3 bodies (framing, comprehension, proof) → closer. Default 5 scenes at each template's preferredDuration, typically 15-20s total. 4 scenes only for explicitly simple/short input; bodies grow beyond 3 only when the user provides 4+ specific assets that each deserve their own scene (cap 6 bodies).",
      "slots": {
        "hook": {
          "bannedTemplateIds": [
            "chatWhatsapp",
            "chatMessenger",
            "appFeed",
            "problemSolution",
            "beforeAfter"
          ],
          "defaultTemplateId": "media"
        },
        "body": {
          "roleBudget": [
            "framing",
            "comprehension",
            "proof"
          ],
          "min": 1,
          "max": 6,
          "default": 3
        },
        "closer": {
          "requiredCategory": "closer",
          "onlyInFinalSlot": true
        }
      },
      "sceneCount": {
        "min": 3,
        "max": 8,
        "default": 5
      },
      "diversity": {
        "noSameCategoryAdjacent": true,
        "noSameTemplateAdjacent": true,
        "adjacencyExemptCategories": [
          "media"
        ]
      }
    }
  },
  "templates": {
    "media": {
      "category": "media",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 1,
      "preferredDuration": 2,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "textColor": {
          "type": "color"
        },
        "confetti": {
          "type": "boolean"
        }
      },
      "defaultVariables": {
        "texts": "Make an impact.",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "textColor": "",
        "confetti": false
      }
    },
    "reaction": {
      "category": "media",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "reactionTag": {
          "type": "enum",
          "required": true,
          "options": [
            "launch",
            "productLaunch",
            "goLive",
            "shipIt",
            "wow",
            "excited",
            "happy",
            "success",
            "done",
            "panic",
            "waiting",
            "celebration",
            "cheers",
            "applause",
            "highFive",
            "teamwork",
            "fail",
            "confused",
            "thinking",
            "thanks",
            "letsGo",
            "manual",
            "office",
            "meeting",
            "deadline",
            "coding",
            "debugging",
            "computer",
            "startup",
            "presentation",
            "sales",
            "growth",
            "money"
          ]
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaType": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "texts": "Still editing manually?",
        "reactionTag": "manual",
        "mediaUrl": "",
        "mediaType": "video"
      }
    },
    "confetti": {
      "category": "celebration",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 1,
      "preferredDuration": 2,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Celebrate.",
        "textColor": ""
      }
    },
    "emojiBurst": {
      "category": "celebration",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 1,
      "preferredDuration": 2,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Let's go!",
        "textColor": ""
      }
    },
    "bigNumber": {
      "category": "data",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 1.5,
      "preferredDuration": 4,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "value": {
          "type": "number",
          "required": true
        },
        "label": {
          "type": "string",
          "required": true
        },
        "prefix": {
          "type": "string"
        },
        "unit": {
          "type": "string"
        },
        "chartColor": {
          "type": "color"
        },
        "textColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "texts": "Our biggest milestone yet.",
        "value": 1000,
        "label": "Total users",
        "prefix": "",
        "unit": "",
        "chartColor": "#00e5a0",
        "textColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "barChart": {
      "category": "data",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "bars": {
          "type": "string"
        },
        "chartColor": {
          "type": "color"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Revenue up 300%.",
        "bars": "30,55,45,80,65,95",
        "chartColor": "#00e5a0",
        "textColor": ""
      }
    },
    "progressRing": {
      "category": "data",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "value": {
          "type": "number",
          "required": true
        },
        "label": {
          "type": "string",
          "required": true
        },
        "unit": {
          "type": "string"
        },
        "chartColor": {
          "type": "color"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Almost there.",
        "value": 75,
        "label": "Complete",
        "unit": "%",
        "chartColor": "#00e5a0",
        "textColor": ""
      }
    },
    "phoneMockup": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "screenMediaUrl": {
          "type": "media"
        },
        "screen1Url": {
          "type": "media"
        },
        "screen2Url": {
          "type": "media"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "See it in action.",
        "screenMediaUrl": "",
        "screen1Url": "",
        "screen2Url": "",
        "textColor": ""
      }
    },
    "webMockup": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "frame": {
          "type": "enum",
          "options": [
            "browser",
            "tablet"
          ]
        },
        "texts": {
          "type": "string",
          "required": true
        },
        "screenMediaUrl": {
          "type": "media"
        },
        "screen1Url": {
          "type": "media"
        },
        "screen2Url": {
          "type": "media"
        },
        "addressBarUrl": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "frame": "browser",
        "texts": "See it in action.",
        "screenMediaUrl": "",
        "screen1Url": "",
        "screen2Url": "",
        "addressBarUrl": "yourapp.com",
        "textColor": ""
      }
    },
    "codeEditor": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "code": {
          "type": "string",
          "required": true
        },
        "filename": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Simple as this.",
        "code": "import { create } from \"vanillasky\";\n\nconst video = await create({\n  prompt: \"Launch trailer\",\n  style: \"cinematic\",\n});\n\nconsole.log(video.url);",
        "filename": "app.ts",
        "textColor": ""
      }
    },
    "terminal": {
      "category": "device",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "command": {
          "type": "string",
          "required": true
        },
        "output": {
          "type": "string"
        },
        "promptPrefix": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "Ship it.",
        "command": "npx vanillasky create --trailer",
        "output": "✓ Scenes composed,✓ Beat-synced to music,✓ Ready to export",
        "promptPrefix": "$",
        "textColor": ""
      }
    },
    "tweet": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 3.5,
      "variableSchema": {
        "authorName": {
          "type": "string",
          "required": true
        },
        "authorHandle": {
          "type": "string"
        },
        "authorVerified": {
          "type": "boolean"
        },
        "message": {
          "type": "string",
          "required": true
        },
        "likes": {
          "type": "number"
        },
        "replies": {
          "type": "number"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "authorName": "Your brand",
        "authorHandle": "",
        "authorVerified": true,
        "message": "Just shipped the new feature 🚀",
        "likes": 602,
        "replies": 19,
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "notification": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "appName": {
          "type": "string",
          "required": true
        },
        "appIcon": {
          "type": "string"
        },
        "message": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "appName": "Reminder",
        "appIcon": "🔔",
        "message": "Believe in your dreams, they will lead you.",
        "textColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "chatMessenger": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 5,
      "preferredDuration": 8,
      "variableSchema": {
        "msg1": {
          "type": "string",
          "required": true
        },
        "msg2": {
          "type": "string",
          "required": true
        },
        "msg3": {
          "type": "string",
          "required": true
        },
        "msg4": {
          "type": "string"
        },
        "dateChip1": {
          "type": "string"
        },
        "dateChip2": {
          "type": "string"
        },
        "msg5": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "theme": "messenger",
        "msg1": "Have you tried it yet?",
        "msg2": "It saves me hours every week",
        "msg3": "And the team loves it",
        "msg4": "Sounds great — sharing access now",
        "msg5": "",
        "dateChip1": "",
        "dateChip2": ""
      }
    },
    "chatWhatsapp": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 5,
      "preferredDuration": 8,
      "variableSchema": {
        "msg1": {
          "type": "string",
          "required": true
        },
        "msg2": {
          "type": "string",
          "required": true
        },
        "msg3": {
          "type": "string",
          "required": true
        },
        "msg4": {
          "type": "string"
        },
        "dateChip1": {
          "type": "string"
        },
        "dateChip2": {
          "type": "string"
        },
        "msg5": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "theme": "whatsapp",
        "msg1": "Have you tried it yet?",
        "msg2": "It saves me hours every week",
        "msg3": "And the team loves it",
        "msg4": "Sounds great — sharing access now",
        "msg5": "",
        "dateChip1": "",
        "dateChip2": ""
      }
    },
    "milestone": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "label": {
          "type": "string",
          "required": true
        },
        "targetNumber": {
          "type": "number",
          "required": true
        },
        "startNumber": {
          "type": "number"
        },
        "badgeText": {
          "type": "string"
        },
        "badgeEmoji": {
          "type": "string"
        },
        "badgeColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "label": "Followers",
        "targetNumber": 10000,
        "startNumber": "",
        "badgeText": "10K Followers!",
        "badgeEmoji": "🎉",
        "badgeColor": "#facc15",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "reviewStack": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "review1Title": {
          "type": "string",
          "required": true
        },
        "review1Body": {
          "type": "string"
        },
        "review1Author": {
          "type": "string"
        },
        "review2Title": {
          "type": "string",
          "required": true
        },
        "review2Body": {
          "type": "string"
        },
        "review2Author": {
          "type": "string"
        },
        "review3Title": {
          "type": "string",
          "required": true
        },
        "review3Body": {
          "type": "string"
        },
        "review3Author": {
          "type": "string"
        },
        "starColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "review1Title": "Life changing app",
        "review1Body": "Been using this for a month and can't imagine going back",
        "review1Author": "Sarah M.",
        "review2Title": "Best in class",
        "review2Body": "Finally an app that just works. No bloat, no nonsense.",
        "review2Author": "Mike R.",
        "review3Title": "Exceeded expectations",
        "review3Body": "Worth every penny. The team clearly cares about quality.",
        "review3Author": "Alex K.",
        "starColor": "#facc15",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "testimonial": {
      "category": "social",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "quote": {
          "type": "string",
          "required": true
        },
        "authorName": {
          "type": "string",
          "required": true
        },
        "authorRole": {
          "type": "string"
        },
        "avatarColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "quote": "Best decision I made this year. Our conversion rate doubled in the first week.",
        "authorName": "Jessica Torres",
        "authorRole": "VP of Marketing, Acme Inc",
        "avatarColor": "#ec4899",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "incomingCall": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "callerName": {
          "type": "string",
          "required": true
        },
        "subtitle": {
          "type": "string"
        },
        "declineLabel": {
          "type": "string"
        },
        "acceptLabel": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "callerName": "Your brand",
        "subtitle": "is calling....",
        "declineLabel": "Decline",
        "acceptLabel": "Accept",
        "textColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "brandMessage": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "brandName": {
          "type": "string",
          "required": true
        },
        "message": {
          "type": "string",
          "required": true
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "brandName": "Your brand",
        "message": "We built this for you.",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "promptInput": {
      "category": "social",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2.5,
      "preferredDuration": 4,
      "variableSchema": {
        "promptText": {
          "type": "string",
          "required": true
        },
        "pillBg": {
          "type": "color"
        },
        "pillTextColor": {
          "type": "color"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        }
      },
      "defaultVariables": {
        "promptText": "Make a launch video for our app",
        "pillBg": "",
        "pillTextColor": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": ""
      }
    },
    "beforeAfter": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 3,
      "preferredDuration": 4.5,
      "variableSchema": {
        "problemLabel": {
          "type": "string"
        },
        "problemHeadline": {
          "type": "string",
          "required": true
        },
        "solutionLabel": {
          "type": "string"
        },
        "solutionHeadline": {
          "type": "string",
          "required": true
        },
        "problemEmojis": {
          "type": "string",
          "required": true
        },
        "solutionEmojis": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "problemLabel": "BEFORE",
        "problemHeadline": "Your calendar today.",
        "solutionLabel": "AFTER",
        "solutionHeadline": "Calmly organized.",
        "problemEmojis": "📅,😰,💼,📊,⏰,💬,📞,🔔",
        "solutionEmojis": "✨,📋,✅,🎯",
        "textColor": ""
      }
    },
    "tripleStats": {
      "category": "data",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "stat1Value": {
          "type": "string",
          "required": true
        },
        "stat1Label": {
          "type": "string",
          "required": true
        },
        "stat2Value": {
          "type": "string",
          "required": true
        },
        "stat2Label": {
          "type": "string",
          "required": true
        },
        "stat3Value": {
          "type": "string",
          "required": true
        },
        "stat3Label": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "By the numbers.",
        "stat1Value": "10K",
        "stat1Label": "Users",
        "stat2Value": "99.9%",
        "stat2Label": "Uptime",
        "stat3Value": "<50ms",
        "stat3Label": "Latency",
        "textColor": ""
      }
    },
    "problemSolution": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 3,
      "preferredDuration": 5.5,
      "variableSchema": {
        "problemLabel": {
          "type": "string"
        },
        "problemText": {
          "type": "string",
          "required": true
        },
        "solutionLabel": {
          "type": "string"
        },
        "solutionText": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "problemLabel": "THE PROBLEM",
        "problemText": "Teams waste 40% of time in meetings",
        "solutionLabel": "THE SOLUTION",
        "solutionText": "AI that summarizes in seconds",
        "textColor": ""
      }
    },
    "cardList": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "items": {
          "type": "string",
          "required": true
        },
        "itemEmojis": {
          "type": "string",
          "required": true
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "What you get.",
        "items": "Automate your savings on energy bills,Cleaner energy without raising your bill,Same account and service guaranteed",
        "itemEmojis": "💰,⚡,🔒",
        "textColor": ""
      }
    },
    "steps": {
      "category": "explainer",
      "usesGlobalBackgroundEffect": true,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "texts": {
          "type": "string",
          "required": true
        },
        "steps": {
          "type": "string",
          "required": true
        },
        "stepEmojis": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "texts": "How it works.",
        "steps": "Describe,Preview,Export",
        "stepEmojis": "✍️,👀,🚀",
        "textColor": ""
      }
    },
    "ctaLogo": {
      "category": "closer",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 3.5,
      "variableSchema": {
        "brandName": {
          "type": "string",
          "required": true
        },
        "url": {
          "type": "string"
        },
        "cta": {
          "type": "string"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "brandName": "VanillaSky",
        "url": "yoursite.com",
        "cta": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": "",
        "textColor": ""
      }
    },
    "ctaMedia": {
      "category": "closer",
      "usesGlobalBackgroundEffect": false,
      "minDuration": 2,
      "preferredDuration": 4,
      "variableSchema": {
        "headline": {
          "type": "string",
          "required": true
        },
        "url": {
          "type": "string"
        },
        "cta": {
          "type": "string"
        },
        "mediaUrl": {
          "type": "media"
        },
        "mediaKeyword": {
          "type": "string"
        },
        "mediaType": {
          "type": "enum",
          "options": [
            "auto",
            "photo",
            "video",
            "gradient"
          ]
        },
        "mediaPoster": {
          "type": "string"
        },
        "textColor": {
          "type": "color"
        }
      },
      "defaultVariables": {
        "headline": "Make every moment count",
        "url": "www.yoursite.com",
        "cta": "",
        "mediaUrl": "",
        "mediaKeyword": "",
        "mediaType": "auto",
        "mediaPoster": "",
        "textColor": ""
      }
    }
  }
};
