import { mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";

const GENERATED_SHEET_FILE = /^(?:sheet|scene\d{2}-.+)\.png$/;

/**
 * Prepare a contact-sheet directory for a fresh render without treating the
 * user-selected directory as disposable. Only files generated by `--sheet`
 * are removed; notes and other user files are preserved.
 */
export function prepareSheetOutputDirectory(outDir) {
  mkdirSync(outDir, { recursive: true });
  for (const file of readdirSync(outDir)) {
    if (GENERATED_SHEET_FILE.test(file)) unlinkSync(join(outDir, file));
  }
}
